@ECommerce.Identity.API_HostAddress = http://localhost:5131

GET {{ECommerce.Identity.API_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{ECommerce.Identity.API_HostAddress}}/api/v1/auth/register
Content-Type: application/json
{
    "username": "testuser",
  "password": "Test123!",
  "email": "test@example.com",
  "firstName": "Test",
  "lastName": "User"
}

###
POST {{ECommerce.Identity.API_HostAddress}}/api/v1/auth/login
Content-Type:application/json

{
  "username": "testuser",
  "password": "Test123!"
}